server:
  port: 7001

spring:
  application:
    name: microservice-zuul-gateway #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss #修改表单提交到后台的日期格式

#eureka配置
eureka:
  client:
    register-with-eureka: true # 服务注册开关
    fetch-registry: true # 服务发现开关
    service-url: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #单机版
      #defaultZone: http://localhost:6001/eureka
      # 集群版: 配置其他的Eureka Server服务端访问地址
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    prefer-ip-address: true #访问路径可以显示IP地址
zuul:
  routes:
    provider-product: # 路由名称，名称任意，路由名称唯一
      path: /product/** #访问路径
      serviceId: microservice-product # 指定服务ID，会自动从Eureka中找到此服务的ip和端口
      stripPrefix: false # 代理转发时是否去掉前缀，false:代理转发时不去掉前缀 例如:为true时 请求 /product/get/1，代理转发到/get/1
    #provider-order:
      #path: /order/**
      #serviceId: microservice-order
      #stripPrefix: false