server:
  port: 8888

#eureka配置
eureka:
  client:
    register-with-eureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetch-registry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    service-url: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #单机版
      #defaultZone: http://localhost:6001/eureka/
      # 集群版: 配置其他的Eureka Server服务端访问地址
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/

## 需要开启 hystrix
feign:
  hystrix:
    enabled: true